# Generated by Django 4.2.1 on 2023-06-03 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventImmediatApp', '0004_rename_eventparticipant_eventsparticipants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsparticipants',
            unique_together={('event', 'user')},
        ),
    ]
